// <auto-generated />
using AppPenilaianSiswa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppPenilaianSiswa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311134123_AddingRoleTable")]
    partial class AddingRoleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppPenilaianSiswa.Models.Mapel", b =>
                {
                    b.Property<int>("MapelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapelId"));

                    b.Property<string>("NamaGuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NamaMapel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MapelId");

                    b.ToTable("Mapels");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.Nilai", b =>
                {
                    b.Property<int>("NilaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NilaiId"));

                    b.Property<int>("MapelId")
                        .HasColumnType("int");

                    b.Property<int>("SiswaId")
                        .HasColumnType("int");

                    b.Property<int>("nilai")
                        .HasColumnType("int");

                    b.HasKey("NilaiId");

                    b.HasIndex("MapelId");

                    b.HasIndex("SiswaId");

                    b.ToTable("Nilais");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.Siswa", b =>
                {
                    b.Property<int>("SiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiswaId"));

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kelas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NamaSiswa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nisn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SiswaId");

                    b.ToTable("Siswas");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.Nilai", b =>
                {
                    b.HasOne("AppPenilaianSiswa.Models.Mapel", "Mapel")
                        .WithMany("Nilais")
                        .HasForeignKey("MapelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppPenilaianSiswa.Models.Siswa", "Siswa")
                        .WithMany("Nilais")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapel");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.User", b =>
                {
                    b.HasOne("AppPenilaianSiswa.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.Mapel", b =>
                {
                    b.Navigation("Nilais");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AppPenilaianSiswa.Models.Siswa", b =>
                {
                    b.Navigation("Nilais");
                });
#pragma warning restore 612, 618
        }
    }
}
